
public class Receita {

	String ID_CODIGO_RECEITA;
	String ID_PRODUTO;
	String CODIGO_RECEITA;
	String ID_CODIGO_PADRAO;
	String COD_RECEITA_INTERESTADUAL;

	public String getID_CODIGO_RECEITA() {
		return ID_CODIGO_RECEITA;
	}

	public void setID_CODIGO_RECEITA(String iD_CODIGO_RECEITA) {
		ID_CODIGO_RECEITA = iD_CODIGO_RECEITA;
	}

	public String getID_PRODUTO() {
		return ID_PRODUTO;
	}

	public void setID_PRODUTO(String iD_PRODUTO) {
		ID_PRODUTO = iD_PRODUTO;
	}

	public String getCODIGO_RECEITA() {
		return CODIGO_RECEITA;
	}

	public void setCODIGO_RECEITA(String cODIGO_RECEITA) {
		CODIGO_RECEITA = cODIGO_RECEITA;
	}

	public String getID_CODIGO_PADRAO() {
		return ID_CODIGO_PADRAO;
	}

	public void setID_CODIGO_PADRAO(String iD_CODIGO_PADRAO) {
		ID_CODIGO_PADRAO = iD_CODIGO_PADRAO;
	}

	public String getCOD_RECEITA_INTERESTADUAL() {
		return COD_RECEITA_INTERESTADUAL;
	}

	public void setCOD_RECEITA_INTERESTADUAL(String cOD_RECEITA_INTERESTADUAL) {
		COD_RECEITA_INTERESTADUAL = cOD_RECEITA_INTERESTADUAL;
	}

	


}
