package modelo;

import java.util.ArrayList;
import java.util.List;

public class Produto {

	String ID_PRODUTO;
	String ID_UNIDADE_MEDIDA;
	String CODIGO_PRODUTO;
	String DESCRICAO_PRODUTO;
	String CODIGO_SUB_PRODUTO;
	String DESCRICAO_SUB_PRODUTO;
	String ID_SITUACAO;
	String CODIGO_CEST;
	String PRECO_MINIMO_INTERNO;
	String PRECO_MINIMO_INTERESTADUAL;
	String ID_GTA;
	String ID_DOF;
	String TRAT_TRIB_ICMS_INTERNO;
	String TRAT_TRIB_ICMS_INTERESTADUAL;
	String TRAT_TRIB_MVA;
	String TRAT_TRIB_RED_BC;
	String TRAT_TRIB_IPI;
	String TRAT_TRIB_ICMS_INTRA_ST;
	String DT_ALTERACAO;
	String ID_EXIGE_DETALHAMENTO;
	String TRAT_TRIB_ICMS_DEBITO;
	String TRAT_TRIB_ICMS_CREDITO;
	String TRAT_TRIB_RED_BC_INTERNO;
	String TRAT_TRIB_RED_BC_INTEREST;
	String TRAT_TRIB_ICMS_CRED_FRETE;
	String TRAT_TRIB_MVA_INTERNO;
	String TRAT_TRIB_MVA_INTEREST;
	String TRAT_TRIB_REDU_ALIQ_INTERNA;
	String TRAT_TRIB_REDU_ALIQ_INTEREST;
	String ID_EXCLUSAO_LOGICA;
	String JUSTIFICATIVA_TRATAMENTO_TRIB;
	String TRAT_TRIB_CRED_PRES_INTERNO;
	String TRAT_TRIB_CRED_PRES_INTEREST;
	String TIPO_CALCULO_CREDITO_PRESUMIDO;

	List<Ncm> listaNcm = new ArrayList<Ncm>();

	ReceitaInterna receita;

	public Produto() {
		// TODO Auto-generated constructor stub
	}

	public String getID_PRODUTO() {
		return ID_PRODUTO;
	}

	public void setID_PRODUTO(String iD_PRODUTO) {
		ID_PRODUTO = iD_PRODUTO;
	}

	public String getID_UNIDADE_MEDIDA() {
		return ID_UNIDADE_MEDIDA;
	}

	public void setID_UNIDADE_MEDIDA(String iD_UNIDADE_MEDIDA) {
		ID_UNIDADE_MEDIDA = iD_UNIDADE_MEDIDA;
	}

	public String getCODIGO_PRODUTO() {
		return CODIGO_PRODUTO;
	}

	public void setCODIGO_PRODUTO(String cODIGO_PRODUTO) {
		CODIGO_PRODUTO = cODIGO_PRODUTO;
	}

	public String getDESCRICAO_PRODUTO() {
		return DESCRICAO_PRODUTO;
	}

	public void setDESCRICAO_PRODUTO(String dESCRICAO_PRODUTO) {
		DESCRICAO_PRODUTO = dESCRICAO_PRODUTO;
	}

	public String getCODIGO_SUB_PRODUTO() {
		return CODIGO_SUB_PRODUTO;
	}

	public void setCODIGO_SUB_PRODUTO(String cODIGO_SUB_PRODUTO) {
		CODIGO_SUB_PRODUTO = cODIGO_SUB_PRODUTO;
	}

	public String getDESCRICAO_SUB_PRODUTO() {
		return DESCRICAO_SUB_PRODUTO;
	}

	public void setDESCRICAO_SUB_PRODUTO(String dESCRICAO_SUB_PRODUTO) {
		DESCRICAO_SUB_PRODUTO = dESCRICAO_SUB_PRODUTO;
	}

	public String getID_SITUACAO() {
		return ID_SITUACAO;
	}

	public void setID_SITUACAO(String iD_SITUACAO) {
		ID_SITUACAO = iD_SITUACAO;
	}

	public String getCODIGO_CEST() {
		return CODIGO_CEST;
	}

	public void setCODIGO_CEST(String cODIGO_CEST) {
		CODIGO_CEST = cODIGO_CEST;
	}

	public String getPRECO_MINIMO_INTERNO() {
		return PRECO_MINIMO_INTERNO;
	}

	public void setPRECO_MINIMO_INTERNO(String pRECO_MINIMO_INTERNO) {
		PRECO_MINIMO_INTERNO = pRECO_MINIMO_INTERNO;
	}

	public String getPRECO_MINIMO_INTERESTADUAL() {
		return PRECO_MINIMO_INTERESTADUAL;
	}

	public void setPRECO_MINIMO_INTERESTADUAL(String pRECO_MINIMO_INTERESTADUAL) {
		PRECO_MINIMO_INTERESTADUAL = pRECO_MINIMO_INTERESTADUAL;
	}

	public String getID_GTA() {
		return ID_GTA;
	}

	public void setID_GTA(String iD_GTA) {
		ID_GTA = iD_GTA;
	}

	public String getID_DOF() {
		return ID_DOF;
	}

	public void setID_DOF(String iD_DOF) {
		ID_DOF = iD_DOF;
	}

	public String getTRAT_TRIB_ICMS_INTERNO() {
		return TRAT_TRIB_ICMS_INTERNO;
	}

	public void setTRAT_TRIB_ICMS_INTERNO(String tRAT_TRIB_ICMS_INTERNO) {
		TRAT_TRIB_ICMS_INTERNO = tRAT_TRIB_ICMS_INTERNO;
	}

	public String getTRAT_TRIB_ICMS_INTERESTADUAL() {
		return TRAT_TRIB_ICMS_INTERESTADUAL;
	}

	public void setTRAT_TRIB_ICMS_INTERESTADUAL(String tRAT_TRIB_ICMS_INTERESTADUAL) {
		TRAT_TRIB_ICMS_INTERESTADUAL = tRAT_TRIB_ICMS_INTERESTADUAL;
	}

	public String getTRAT_TRIB_MVA() {
		return TRAT_TRIB_MVA;
	}

	public void setTRAT_TRIB_MVA(String tRAT_TRIB_MVA) {
		TRAT_TRIB_MVA = tRAT_TRIB_MVA;
	}

	public String getTRAT_TRIB_RED_BC() {
		return TRAT_TRIB_RED_BC;
	}

	public void setTRAT_TRIB_RED_BC(String tRAT_TRIB_RED_BC) {
		TRAT_TRIB_RED_BC = tRAT_TRIB_RED_BC;
	}

	public String getTRAT_TRIB_IPI() {
		return TRAT_TRIB_IPI;
	}

	public void setTRAT_TRIB_IPI(String tRAT_TRIB_IPI) {
		TRAT_TRIB_IPI = tRAT_TRIB_IPI;
	}

	public String getTRAT_TRIB_ICMS_INTRA_ST() {
		return TRAT_TRIB_ICMS_INTRA_ST;
	}

	public void setTRAT_TRIB_ICMS_INTRA_ST(String tRAT_TRIB_ICMS_INTRA_ST) {
		TRAT_TRIB_ICMS_INTRA_ST = tRAT_TRIB_ICMS_INTRA_ST;
	}

	public String getDT_ALTERACAO() {
		return DT_ALTERACAO;
	}

	public void setDT_ALTERACAO(String dT_ALTERACAO) {
		DT_ALTERACAO = dT_ALTERACAO;
	}

	public String getID_EXIGE_DETALHAMENTO() {
		return ID_EXIGE_DETALHAMENTO;
	}

	public void setID_EXIGE_DETALHAMENTO(String iD_EXIGE_DETALHAMENTO) {
		ID_EXIGE_DETALHAMENTO = iD_EXIGE_DETALHAMENTO;
	}

	public String getTRAT_TRIB_ICMS_DEBITO() {
		return TRAT_TRIB_ICMS_DEBITO;
	}

	public void setTRAT_TRIB_ICMS_DEBITO(String tRAT_TRIB_ICMS_DEBITO) {
		TRAT_TRIB_ICMS_DEBITO = tRAT_TRIB_ICMS_DEBITO;
	}

	public String getTRAT_TRIB_ICMS_CREDITO() {
		return TRAT_TRIB_ICMS_CREDITO;
	}

	public void setTRAT_TRIB_ICMS_CREDITO(String tRAT_TRIB_ICMS_CREDITO) {
		TRAT_TRIB_ICMS_CREDITO = tRAT_TRIB_ICMS_CREDITO;
	}

	public String getTRAT_TRIB_RED_BC_INTERNO() {
		return TRAT_TRIB_RED_BC_INTERNO;
	}

	public void setTRAT_TRIB_RED_BC_INTERNO(String tRAT_TRIB_RED_BC_INTERNO) {
		TRAT_TRIB_RED_BC_INTERNO = tRAT_TRIB_RED_BC_INTERNO;
	}

	public String getTRAT_TRIB_RED_BC_INTEREST() {
		return TRAT_TRIB_RED_BC_INTEREST;
	}

	public void setTRAT_TRIB_RED_BC_INTEREST(String tRAT_TRIB_RED_BC_INTEREST) {
		TRAT_TRIB_RED_BC_INTEREST = tRAT_TRIB_RED_BC_INTEREST;
	}

	public String getTRAT_TRIB_CRED_PRES_INTERNO() {
		return TRAT_TRIB_CRED_PRES_INTERNO;
	}

	public void setTRAT_TRIB_CRED_PRES_INTERNO(String tRAT_TRIB_CRED_PRES_INTERNO) {
		TRAT_TRIB_CRED_PRES_INTERNO = tRAT_TRIB_CRED_PRES_INTERNO;
	}

	public String getTRAT_TRIB_CRED_PRES_INTEREST() {
		return TRAT_TRIB_CRED_PRES_INTEREST;
	}

	public void setTRAT_TRIB_CRED_PRES_INTEREST(String tRAT_TRIB_CRED_PRES_INTEREST) {
		TRAT_TRIB_CRED_PRES_INTEREST = tRAT_TRIB_CRED_PRES_INTEREST;
	}

	public String getTIPO_CALCULO_CREDITO_PRESUMIDO() {
		return TIPO_CALCULO_CREDITO_PRESUMIDO;
	}

	public void setTIPO_CALCULO_CREDITO_PRESUMIDO(String tIPO_CALCULO_CREDITO_PRESUMIDO) {
		TIPO_CALCULO_CREDITO_PRESUMIDO = tIPO_CALCULO_CREDITO_PRESUMIDO;
	}

	public String getTRAT_TRIB_ICMS_CRED_FRETE() {
		return TRAT_TRIB_ICMS_CRED_FRETE;
	}

	public void setTRAT_TRIB_ICMS_CRED_FRETE(String tRAT_TRIB_ICMS_CRED_FRETE) {
		TRAT_TRIB_ICMS_CRED_FRETE = tRAT_TRIB_ICMS_CRED_FRETE;
	}

	public String getTRAT_TRIB_MVA_INTERNO() {
		return TRAT_TRIB_MVA_INTERNO;
	}

	public void setTRAT_TRIB_MVA_INTERNO(String tRAT_TRIB_MVA_INTERNO) {
		TRAT_TRIB_MVA_INTERNO = tRAT_TRIB_MVA_INTERNO;
	}

	public String getTRAT_TRIB_MVA_INTEREST() {
		return TRAT_TRIB_MVA_INTEREST;
	}

	public void setTRAT_TRIB_MVA_INTEREST(String tRAT_TRIB_MVA_INTEREST) {
		TRAT_TRIB_MVA_INTEREST = tRAT_TRIB_MVA_INTEREST;
	}

	public String getTRAT_TRIB_REDU_ALIQ_INTERNA() {
		return TRAT_TRIB_REDU_ALIQ_INTERNA;
	}

	public void setTRAT_TRIB_REDU_ALIQ_INTERNA(String tRAT_TRIB_REDU_ALIQ_INTERNA) {
		TRAT_TRIB_REDU_ALIQ_INTERNA = tRAT_TRIB_REDU_ALIQ_INTERNA;
	}

	public String getTRAT_TRIB_REDU_ALIQ_INTEREST() {
		return TRAT_TRIB_REDU_ALIQ_INTEREST;
	}

	public void setTRAT_TRIB_REDU_ALIQ_INTEREST(String tRAT_TRIB_REDU_ALIQ_INTEREST) {
		TRAT_TRIB_REDU_ALIQ_INTEREST = tRAT_TRIB_REDU_ALIQ_INTEREST;
	}

	public String getID_EXCLUSAO_LOGICA() {
		return ID_EXCLUSAO_LOGICA;
	}

	public void setID_EXCLUSAO_LOGICA(String iD_EXCLUSAO_LOGICA) {
		ID_EXCLUSAO_LOGICA = iD_EXCLUSAO_LOGICA;
	}

	public String getJUSTIFICATIVA_TRATAMENTO_TRIB() {
		return JUSTIFICATIVA_TRATAMENTO_TRIB;
	}

	public void setJUSTIFICATIVA_TRATAMENTO_TRIB(String jUSTIFICATIVA_TRATAMENTO_TRIB) {
		JUSTIFICATIVA_TRATAMENTO_TRIB = jUSTIFICATIVA_TRATAMENTO_TRIB;
	}

	public List<Ncm> getListaNcm() {
		return listaNcm;
	}

	public void setListaNcm(List<Ncm> listaNcm) {
		this.listaNcm = listaNcm;
	}

	public ReceitaInterna getReceita() {
		return receita;
	}

	public void setReceita(ReceitaInterna receita) {
		this.receita = receita;
	}

	@Override
	public String toString() {
		return "Produto [ID_PRODUTO=" + ID_PRODUTO + ", ID_UNIDADE_MEDIDA=" + ID_UNIDADE_MEDIDA + ", CODIGO_PRODUTO="
				+ CODIGO_PRODUTO + ", DESCRICAO_PRODUTO=" + DESCRICAO_PRODUTO + ", CODIGO_SUB_PRODUTO="
				+ CODIGO_SUB_PRODUTO + ", DESCRICAO_SUB_PRODUTO=" + DESCRICAO_SUB_PRODUTO + ", ID_SITUACAO="
				+ ID_SITUACAO + ", CODIGO_CEST=" + CODIGO_CEST + ", PRECO_MINIMO_INTERNO=" + PRECO_MINIMO_INTERNO
				+ ", PRECO_MINIMO_INTERESTADUAL=" + PRECO_MINIMO_INTERESTADUAL + ", ID_GTA=" + ID_GTA + ", ID_DOF="
				+ ID_DOF + ", TRAT_TRIB_ICMS_INTERNO=" + TRAT_TRIB_ICMS_INTERNO + ", TRAT_TRIB_ICMS_INTERESTADUAL="
				+ TRAT_TRIB_ICMS_INTERESTADUAL + ", TRAT_TRIB_MVA=" + TRAT_TRIB_MVA + ", TRAT_TRIB_RED_BC="
				+ TRAT_TRIB_RED_BC + ", TRAT_TRIB_IPI=" + TRAT_TRIB_IPI + ", TRAT_TRIB_ICMS_INTRA_ST="
				+ TRAT_TRIB_ICMS_INTRA_ST + ", DT_ALTERACAO=" + DT_ALTERACAO + ", ID_EXIGE_DETALHAMENTO="
				+ ID_EXIGE_DETALHAMENTO + ", TRAT_TRIB_ICMS_DEBITO=" + TRAT_TRIB_ICMS_DEBITO
				+ ", TRAT_TRIB_ICMS_CREDITO=" + TRAT_TRIB_ICMS_CREDITO + ", TRAT_TRIB_RED_BC_INTERNO="
				+ TRAT_TRIB_RED_BC_INTERNO + ", TRAT_TRIB_RED_BC_INTEREST=" + TRAT_TRIB_RED_BC_INTEREST
				+ ", TRAT_TRIB_CRED_PRES_INTERNO=" + TRAT_TRIB_CRED_PRES_INTERNO + ", TRAT_TRIB_ICMS_CRED_FRETE="
				+ TRAT_TRIB_ICMS_CRED_FRETE + ", TRAT_TRIB_MVA_INTERNO=" + TRAT_TRIB_MVA_INTERNO
				+ ", TRAT_TRIB_MVA_INTEREST=" + TRAT_TRIB_MVA_INTEREST + ", TRAT_TRIB_REDU_ALIQ_INTERNA="
				+ TRAT_TRIB_REDU_ALIQ_INTERNA + ", TRAT_TRIB_REDU_ALIQ_INTEREST=" + TRAT_TRIB_REDU_ALIQ_INTEREST
				+ ", ID_EXCLUSAO_LOGICA=" + ID_EXCLUSAO_LOGICA + ", JUSTIFICATIVA_TRATAMENTO_TRIB="
				+ JUSTIFICATIVA_TRATAMENTO_TRIB + ", TRAT_TRIB_CRED_PRES_INTEREST=" + TRAT_TRIB_CRED_PRES_INTEREST
				+ ", TIPO_CALCULO_CREDITO_PRESUMIDO=" + TIPO_CALCULO_CREDITO_PRESUMIDO + ", listaNcm=" + listaNcm
				+ ", receita=" + receita + "]";
	}

}
